config/routes.rb
Rails.application.routes.draw do

  root to: "sites#index"

  resources :users, except: [:new]
  resources :posts
  
  get "/sign_up", to: "users#new"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

  get "/logout", to: "sessions#destroy", as: "logout"

  get "/city/:id", to: "cities#show", as: "city"
  get "/cities", to: "cities#index"
  
end



#    Prefix Verb   URI Pattern               Controller#Action
#      root GET    /                         sites#index
#     users GET    /users(.:format)          users#index
#           POST   /users(.:format)          users#create
# edit_user GET    /users/:id/edit(.:format) users#edit
#      user GET    /users/:id(.:format)      users#show
#           PATCH  /users/:id(.:format)      users#update
#           PUT    /users/:id(.:format)      users#update
#           DELETE /users/:id(.:format)      users#destroy
#     posts GET    /posts(.:format)          posts#index
#           POST   /posts(.:format)          posts#create
#  new_post GET    /posts/new(.:format)      posts#new
# edit_post GET    /posts/:id/edit(.:format) posts#edit
#      post GET    /posts/:id(.:format)      posts#show
#           PATCH  /posts/:id(.:format)      posts#update
#           PUT    /posts/:id(.:format)      posts#update
#           DELETE /posts/:id(.:format)      posts#destroy
#   sign_up GET    /sign_up(.:format)        users#new
#     login GET    /login(.:format)          sessions#new
#           POST   /login(.:format)          sessions#create
#    logout GET    /logout(.:format)         sessions#destroy

app/models/city.rb
class City < ActiveRecord::Base
	has_many :users
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :city
	belongs_to :user

	validates :title, presence: true, length: { maximum: 200 }
	validates :content, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	belongs_to :city

	has_many :posts
	#validates :password, confirmation: true
	#validates :password_confirmation, presence: true
	before_save { |user| user.email = email.downcase }

	validates :first_name, presence: true, length: { maximum: 25 }
	validates :last_name, presence: true, length: { maximum: 25 }, :on => :create
	validates :password, presence: true, length: { minimum: 6 }, :on => :create
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
	                uniqueness: { case_sensitive: false, message: "That email has already been taken!" }, :on => :create

	include Gravtastic
	gravtastic

	def self.confirm(params)
		@user = User.find_by({email: params[:email]})
		@user.try(:authenticate, params[:password])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #include Pundit

  protect_from_forgery with: :exception

  include SessionsHelper
  
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	def index
		@cities = City.all
	end

	def show 

		@city = City.find(params[:id])
		@cityposts = @city.posts
	end

	private
	def city_params
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :logged_in?

	# posts GET    /posts(.:format)          posts#index
	def index
		@posts = Post.all
		render :index
	end

	# new_post GET    /posts/new(.:format)      posts#new
	def new
		@post = Post.new
		render :new
	end

	# POST   /posts(.:format)          posts#create
	def create
		@post = current_user.posts.new(post_params)
		if @post.save
			redirect_to post_path @post.id
		else 
			flash[:nopost] = @post.errors
			redirect_to new_post_path
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
		render :edit
	end

	def update
    	@post = Post.find params[:id]
    	if @post.update(post_params) 
      		redirect_to "/posts/#{@post.id}"
    	else
      		@errors = @post.errors.messages
    	end
	end

	# DELETE /posts/:id(.:format)      posts#destroy
	def destroy
		session[:return_to] ||= request.referer
    	post = Post.find params[:id]
    	post.destroy
    	redirect_to session.delete(:return_to)
	end

	#stored these params here for easy reuse
	private
	def post_params
		params.require(:post).permit(:id, :user_id, :title, :content, :city_id)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.confirm(login_params)
		if @user
			login(@user)
			puts "User logged in"
			redirect_to user_path @user.id
		else
			redirect_to login_path
		end
	end
	
	def destroy
		logout
		redirect_to root_path
	end

	private
	def login_params
		params.require(:user).permit(:email, :password)
	end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
  	@users = User.all
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :logged_in?, only: [:show, :edit, :index]

	def index
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
		   login(@user)
		   redirect_to user_path @user
		else
		   flash[:nosignup] = @user.errors
		   redirect_to sign_up_path
		end
	end


	def show
		@user = User.find(params[:id])
		@posts = @user.posts
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params) 
		redirect_to user_path current_user.id
	end

	private

	def user_params
		params.require(:user).permit(:id, :first_name, :last_name, :email, :password, :password_confirmation, :city_id)
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user, size)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def login(user)
		session[:user_id] = user.id
		@current_user = user
	end

	def current_user
		if session[:user_id] 
			@current_user ||= User.find(session[:user_id])
		else 
			@current_user = nil
		end
	end

	def logged_in?
		if session[:user_id] == nil
			redirect_to "/login"
		end
	end

	def logout
		@current_user = session[:user_id] = nil
	end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/index.html.erb
<%= render partial: "/users/nav", locals: {user: @user} %>
<h1 class="text-center">Cities</h1>

<div class="container-fluid">
	<div class="row">
		<% @cities.each do |city| %>
			<div class="col-xs-6 col-sm-4 gallery" style="text-align:center;">
				<img class="thumbnail img-responsive" src="<%= city.picture %>" width="350px" height="250px" >
				<h4 class="text-center " style="display:in-line;"><%= link_to "#{city.name}", city_path(city.id)  %>  (<%= city.posts.length %>) </h4>
			</div>
		<% end %>
	</div>
</div>


<%= render partial: "/users/footer" %>

app/views/cities/show.html.erb
<%= render partial: "/users/nav" %>
<div class="container">
<div class="row margin50">
<div class="col-md-6 col-md-offset-3">
  <div class= "text-center">
  <h1><%= @city.name %></h1>
</div>
  <br>
  <div class= "text-center"><img class="city" src="<%= @city.picture %>">
  <div>&nbsp</div>
  <div id="map" class: "col-md-6 col-md-offset-3" style="width: 775px; height: 300px;"></div> 

  <h2>Recent Posts</h2>
  </div>
  <br>
  <br>
	 <% @cityposts.reverse.each do |p| %>
      <div class="row well"> 
      <% if current_user == p.user %>   
      <%= button_to " x ", post_path(p.id), :class => "btn btn-xs btn-danger pull-right", :method => :delete,  data: { confirm: "Are you sure you want to delete #{p.title}?" } %>
      <% end%>  
      <div class="col-md-8">
        <h3><%= link_to "#{p.title}", post_path(p.id) %></h3> 
        <div class="col-md-3 row top-margin20">
      <% if current_user == p.user %>
        <%= button_to "Edit Post", edit_post_path(p.id), :class => "btn btn-xs btn-primary", :method => :get  %>
      <% end%> 
      </div>
        <!-- <span class="label label-default"><%= p.city.name %></span>-->
      </div>
    </div>

    
<%= render partial: "/users/footer" %>


    <% end %>
    </div>
  </div>

</div>
<script> 

   var address = "<%= @city.name %>";

   var map = new google.maps.Map(document.getElementById('map'), { 
       mapTypeId: google.maps.MapTypeId.TERRAIN,
       zoom: 6
   });

   var geocoder = new google.maps.Geocoder();

   geocoder.geocode({
      'address': address
   }, 
   function(results, status) {
      if(status == google.maps.GeocoderStatus.OK) {
         new google.maps.Marker({
            position: results[0].geometry.location,
            map: map
         });
         map.setCenter(results[0].geometry.location);
      }
   });

</script> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vagablog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
</head>
<body>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/posts/edit.html.erb
<%= render partial: "users/nav", locals: {user: @user} %>
<div class="row margin50">
	<h1 class="col-md-4 col-md-offset-3">Edit this post</h1>

	<div>
	<%= form_for @post do |f|%>

		<div class="row">
			<div class="col-md-3 col-md-offset-3"><%= f.text_field :title, placeholder: "Post title", class: "form-control" %></div>
		</div><br>

		<div class="row">
			<div class="col-md-5 col-md-offset-3"><%= f.text_area :content, placeholder: "Post content", class: "form-control", rows: "10" %></div>
		</div><br>

		<div class="row">
			<div class="col-md-3 col-md-offset-3"><%= f.submit "Update", class: "btn btn-default" %></div>
		</div><br>

		<% end %>


<%= render partial: "/users/footer" %>

	</div>
</div>

app/views/posts/index.html.erb
<h1>Posts#index</h1>

<% @posts.each do |f| %>
<ul>
	<li><%= f.title %></li>
	<li><%= f.content %></li>
</ul>
<% end %>


<%= render partial: "/users/footer" %>

app/views/posts/new.html.erb
<%= render partial: "users/nav", locals: {user: @user} %>
<div class="col-md-5 col-md-offset-3 margin50">
	<% if flash['nopost'] %>
		<% flash['nopost'].each do |k,v| %>
			<div class="alert-danger text-center"><%= p v[0] %></div>
		<% end %>
	<% end %>
</div>
<h1 class="col-md-5 col-md-offset-3">Make a new post</h1>
<div class="row margin50"></div>
</div>	
<%= form_for(@post) do |f|%>
	<div class="row">
	<div class="col-md-3 col-md-offset-3 form-group"><%= f.text_field :title, placeholder: "Post title", class: "form-control" %></div>
	</div>
	<div class="row"><br>
	<div class="col-md-5 col-md-offset-3 form-group"><%= f.text_area :content, placeholder: "Post content", class: "form-control", rows: "10" %></div>
	</div>
	<div class="row">
	<div class="col-md-3 col-md-offset-3 form-group"><%= f.collection_select(:city_id, City.all, :id, :name) %></div>
	</div>
	<div class="row">
	<div class="col-md-5 col-md-offset-3 form-group"><%= f.submit "Submit", class: "btn btn-default" %></div>
	</div>
<% end %>

</div>


<%= render partial: "/users/footer" %>

<script>
$(document).ready(function() {
	$('#post_city_id').addClass('form-control');
});
</script>

app/views/posts/show.html.erb
<%= render partial: "users/nav", locals: {user: @user} %>
<!-- <h1>Post #<%= @post.id %></h1> -->
<div class="row margin50">
	<div class="col-sm-3" id="sidebar">
		<h1 class"col-xs-9"><%= @post.user.first_name %></h1>
		<a class="logo"><%= image_tag avatar_url(current_user, 200) %></a>
	</div>

	<div class="row">
		<div class="col-xs-4 col-md-offset-3"><h2><%= @post.title %></h2></div>
		<hr class="col-xs-5 col-md-offset-3">
		<div class="col-sm-6 col-md-offset-3"><%= @post.content %></div>
	</div>
</div>

<div class="col-md-9"><blockquote class="blockquote-reverse"><%= link_to "Back to Profile", user_path(@post.user_id) %></blockquote>
</div>


<%= render partial: "/users/footer" %>

app/views/sites/about.html.erb
<h1>Sites#about</h1>
<p>Find me in app/views/sites/about.html.erb</p>

app/views/sites/contact.html.erb
<h1>Sites#contact</h1>
<p>Find me in app/views/sites/contact.html.erb</p>

app/views/sites/index.html.erb
<!--<script src="/app/assets/javascripts/jquery.tubular.1.0.js" type="text/javascript"></script>-->

<%= render partial: "users/nav", locals: {user: @user} %>
<div id="wrapper">
	<div class="row margin50">
		<div class="col-md-9 center-block clear-float">
			<!-- iframe for video

			<iframe class="center-block clear-float" width="960" height="540" src="https://www.youtube.com/embed/UGnrT0F-Igs?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen style="margin-top: 60px;"></iframe>
 			-->

		</div>
	</div><!-- end row -->

	<div class="row min-height100" style="margin-top: 200px;">

		<div class="col-md-9 center-block clear-float">
			<div class="row" style="padding-left: 100px;">
				<div class="col-md-3 col-md-offset-2 btn btn-danger">
					<%= link_to '<button class="btn btn-block btn-danger center-block">Sign up &amp; travel with us</button>'.html_safe, sign_up_path %>
					
				</div>
				<div class="col-md-3 col-md-offset-1 btn btn-warning">				
					<%= link_to '<button class="btn btn-block btn-warning center-block">Sign in and share!</button>'.html_safe, login_path %>
					
				</div>
			</div>
		</div>

	</div>
	<div style="clear: both;">&nbsp;</div>
		<div id="footer" style="margin-bottom: 0;">
			<p class="text-center">&copy; Vagabond Travels, Inc. <span style=
			"margin-left: 20px;">There are currently 653,42<%= @users.length %> registered users.</span></p>
		</div>
</div>
<script>
$(document).ready(function() {
	$('#wrapper').tubular({videoId: 'UGnrT0F-Igs'});
});
</script>

app/views/users/_footer.html.erb
<div id="footer" style="margin-bottom: 0;">
	<p class="text-center">&copy; Vagabond Travels, Inc. 
	
</div>

app/views/users/_nav.html.erb
  <link href='http://fonts.googleapis.com/css?family=Berkshire+Swash' rel='stylesheet' type='text/css'>
  <!-- Fixed navbar -->
  <div class="navbar navbar-default navbar-fixed-top navbar-inverse" id="home">
    <div class="container">
      <div class="navbar-header">

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <span id="logo">V</span><a class="navbar-brand" style="color: #ffffff; font-size: 30px; margin-top:10px;" href="<%= if session[:user_id] then user_path current_user.id else end  %>">Vagabond</a>

      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
        <% if session[:user_id] %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= if params[:controller] == 'cities' && params[:action] == 'show' then @city.name else current_user.email end %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li class="dropdown-header">User Menu</li>
              <li><a href="<%= user_path current_user.id%>">Profile</a></li>
              <li><a href="<%= edit_user_path current_user.id%>">Edit Profile</a></li>
              <li><a href="/posts/new">New Post</a></li>
              <li><a href="/cities">Cities</a></li>
              <li><a href="/logout">Logout</a></li>
            </ul>
        <% else %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= if params[:controller] == 'cities' && params[:action] == 'show' then @city.name else "Welcome" end %>  
          <b class="caret"></b></a>
            <ul class="dropdown-menu">
            <li><a href="<%= login_path %>">Login</a></li>
            <li> <a href="<%= sign_up_path %>">Sign up</a></li>
            </ul>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
  

app/views/users/edit.html.erb
<%= render partial: "users/nav", locals: {user: @user} %>
<div class="row margin50">
	<h1 class="col-md-3 col-md-offset-4">Edit my profile</h1>

	<%= form_for @user do |u| %>
	
	<div class="row">
		<div class="col-md-3 col-md-offset-4 form-group"><%= u.text_field :first_name, placeholder: "First Name", class: "form-control" %></div>
	</div>

	<div class="row">
		<div class="col-md-3 col-md-offset-4 form-group"><%= u.text_field :last_name, placeholder: "Last Name", class: "form-control" %></div>
	</div>

	<div class="row">
		<div class="col-md-3 col-md-offset-4 form-group"><%= u.collection_select(:city_id, City.all, :id, :name) %></div>
	</div>

	<div class="row">
		<div class="col-md-3 col-md-offset-4 form-group"><%= u.submit "Update Profile", class: "btn btn-default" %></div>
	</div>
<% end %>
</div>


<%= render partial: "/users/footer" %>

<script>
$(document).ready(function() {
	$('#user_city_id').addClass('form-control');
});
</script>

app/views/users/new.html.erb
<div class= "col-md-3 col-md-offset-4"><% if flash['nosignup'] %>
		<% flash['nosignup'].each do |k,v| %>
			<div class="alert-danger text-center"><%= p v[0] %></div>
		<% end %>
	<% end %>
</div>
<h1 class="col-md-3 col-md-offset-4 text-center">Sign Up Here</h1>
<%= form_for @user do |u| %>
	<div class="row">
		<div class="col-md-3 col-md-offset-4"><%= u.text_field :first_name, placeholder: "First Name", class: "form-control" %></div><br>
	</div><br>
	
	<div class="row">
		<div class="col-md-3 col-md-offset-4"><%= u.text_field :last_name, placeholder: "Last Name", class: "form-control" %></div><br>
	</div><br>

	<div class="row">
		<div class="col-md-3 col-md-offset-4"><%= u.text_field :email, placeholder: "Email", class: "form-control" %></div><br>
	</div><br>

	<div class="row">
		<div class="col-md-3 col-md-offset-4"><%= u.password_field :password, placeholder: "Password", class: "form-control" %></div><br>
	</div><br>

	<div class="row">
		<div class="col-md-3 col-md-offset-4"><%= u.password_field :password_confirmation, placeholder: "Confirm Password", class: "form-control" %></div><br>
	</div><br>

	<div class="row">
		<div class="col-md-3 col-md-offset-4 text-center"><%= u.collection_select(:city_id, City.all, :id, :name) %></div><br>
	</div><br>

	<div class="col-md-3 col-md-offset-4"><%= u.submit "Sign Up", class: "btn btn-default center-block" %></div><br>
<% end %>


<%= render partial: "/users/footer" %>

app/views/users/show.html.erb
<%= render partial: "users/nav", locals: {user: @user} %>

<!--<div class="wrapper">
    <div class="box"> -->
    <div class="row margin50">
        <!-- sidebar -->
        <div class="column col-sm-3" id="sidebar">
        <a class="logo"><%= image_tag( session[:user_id] ? avatar_url(current_user, 200) : "http://farm4.staticflickr.com/3038/2980688504_53278a520d_z.jpg") %></a>
        <div class="profile-item"><%= @user.first_name %></div>
        <div class="profile-item"><%= @user.city.name %></div>
        <br>
        <div class="profile-item">Member since: <%= @user.created_at.strftime("%m/%d/%y") %></div>
        <%= button_to "Make New Post", new_post_path, :class => "btn btn-xs btn-primary post-button", :method => :get  %>
        </div>
        <!-- /sidebar -->
      
        <!-- main -->
        <div class="column col-sm-9" id="main">
            <!-- <div class="padding"> -->
            <div class="row">
            <!-- <div class="full col-sm-9"> -->
                <!-- content -->
                <div class="page-header text-muted">Posts</div> 
            </div>
                
                <% @posts.reverse.each do |p| %>                   
                <!--/stories-->
            <div class="row well">    
                <%= button_to " x ", post_path(p.id), :class => "btn btn-xs btn-danger pull-right", :method => :delete,  data: { confirm: "Are you sure you want to delete #{p.title}?" } %>
                <div class="col-sm-10">
                    <h3><%= link_to "#{p.title}", post_path(p.id) %> <span class="small"><%= p.city.name %></span></h3>
                        <%= button_to "Edit Post", edit_post_path(p.id), :class => "btn btn-xs btn-primary top-margin20", :method => :get  %> 
                </div>
            </div>

                <div class="col-md-12 row">

                </div>
                 <div class="row divider">    
                   <div class="col-sm-12"><hr></div>
                </div>
                <% end %>
                
            </div>
            <!-- </div> -->
        </div>
        <!-- </div> -->
    </div>
    <!-- </div> 
</div>-->

<%= render partial: "/users/footer" %>